# Créer la table d'export au format synthèse adapté si elle n'existe pas
import_format = Table(table, meta,
    Column('unique_id_sinp', UUID(as_uuid=True), primary_key=True),
    Column('unique_id_sinp_grp',UUID(as_uuid=True)),
    Column('entity_source_pk_value', String),
    Column('id_dataset',Integer),
    Column('cd_nomenclature_geo_object_nature',String(50)),
    Column('cd_nomenclature_grp_typ',String(50)),
    Column('cd_nomenclature_obs_meth',String(50)),
    Column('cd_nomenclature_obs_technique',String(50)),
    Column('cd_nomenclature_bio_status',String(50)),
    Column('cd_nomenclature_bio_condition',String(50)),
    Column('cd_nomenclature_naturalness',String(50)),
    Column('cd_nomenclature_exist_proof',String(50)),
    Column('cd_nomenclature_valid_status',String(50)),
    Column('cd_nomenclature_diffusion_level',String(50)),
    Column('cd_nomenclature_life_stage',String(50)),
    Column('cd_nomenclature_sex',String(50)),
    Column('cd_nomenclature_obj_count',String(50)),
    Column('cd_nomenclature_type_count',String(50)),
    Column('cd_nomenclature_sensitivity',String(50)),
    Column('cd_nomenclature_observation_status',String(50)),
    Column('cd_nomenclature_blurring',String(50)),
    Column('cd_nomenclature_source_status',String(50)),
    Column('count_min', Integer),
    Column('count_max', Integer),
    Column('cd_nom', Integer),
    Column('nom_cite',String(1000)),
    Column('meta_v_taxref',String(50)),
    Column('sample_number_proof',String),
    Column('digital_proof',Sting),
    Column('non_digital_proof',String),
    Column('altitude_min',Integer),
    Column('altitude_max',Integer),
    Column('the_geom20_4326',Geometry("GEOMETRY", 4326)),
    Column('the_geom_point',Geometry("GEOMETRY", 4326)),
    Column('the_geom_local',Geometry("GEOMETRY", LOCAL_SRID)),
    Column('date_min', DateTime),
    Column('date_max', DateTime),
    Column('validator',String(1000)),
    Column('validation_comment',String),
    Column('observers',String(1000)),
    Column('determiner',String(1000)),
    Column('cd_nomenclature_determination_method',String(50)),
    Column('meta_validation_date',DateTime),
    Column('meta_create_date',DateTime),
    Column('meta_update_date',DateTime),
    Column('last_action',String(1)),
    Column('comment_context',String),
    Column('comment_description',String),
    Column('import_name',String(1000))
)
