name: pytest

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        geonature_ref: ["master", "develop"]
    uses: pnx-si/geonature/.github/workflows/gn-module-pytest.yml@feat/gn-module-pytest
    with:
      geonature_ref: ${{ matrix.geonature_ref }}
